84 front modify html websites UI upload form
massalabs/thyra pull request #106
Opened 2022-09-12 12:41 UTC by SebastienValla

to be merged with issue 95 backend
AS IS :

    2 actions are needed from the user
        for deploying the websiteCreator
        to upload the zipped website

TO BE :

    One form composed of : (check mockups)
        the dns name input
        a file uploader button
add a pattern for DNS names
add a filter for only zip

2022-09-13 15:22 UTC, ASAPSegfault commented on int/api/webcreator.go
> +	archive, err := ioutil.ReadAll(params.Zipfile)
ioutil needs to be changed to io or os. Also the package import needs to be updated to match the new package.
Source : https://pkg.go.dev/io/ioutil

2022-09-14 17:09 UTC, SlnPons commented
UI things to address: 
1. the tooltip for the website name:
- the icon needs to be bigger. We need to see that it's a i.
- the text needs to be displayed at the top of the field currently it's displayed at the bottom of the module (see attached). If it's easier, you could remove the icon and always display the text below the text box. (like Google)
<img width="384" alt="image" src="https://user-images.githubusercontent.com/109611779/190156677-c6898187-f61a-4083-beb5-fa0a4a17467e.png">
<img width="385" alt="image" src="https://user-images.githubusercontent.com/109611779/190156927-0caa1275-da26-46d2-86c3-d11f52d937bd.png">
2. Buttons:
a. wallet button should be 'disable' mode (eg: https://getbootstrap.com/docs/5.2/components/buttons/#disabled-state) - for the colour I suggest either the original colour (red) or grey.
b. import website button should be responsive to the text length 
3. The module itself: 
- remove the border (to see if it looks better)
- increase padding between the 'import from' and 'upload' button (should be higher than 24px to look good normally but let's see)
4. Upload button in the table --> 'edit'
5. "Decentralised website storing" title 
- Should be "Decentralised website storage" 
- Should be left aligned (currently centered)
6. Add a title to the module: "Upload your website"
- centered in the module

2022-09-15 08:52 UTC, Trottoir requested changes
You need to care about what files you are pushing
When not needed, don't put generated files if only Header is changing.
We'll not have that problem anymore when that issue will be resolved => [https://github.com/massalabs/thyra/issues/70](https://github.com/massalabs/thyra/issues/70)

Also, we don't need the png & the svg info file.

When an icon is needed, pls check the icon library from bootstrap [https://icons.getbootstrap.com/](https://icons.getbootstrap.com/)

2022-09-15 08:52 UTC, Trottoir commented on pkg/front/errors.go
>  // GENERATED BY textFileToGoConst
No need to push that one

2022-09-15 13:39 UTC, Trottoir commented on pkg/onchain/website/browser.go
> +	case ".svg":
No need that anymore as we use the icon from bootstrap

2022-09-15 13:39 UTC, Trottoir commented on pkg/front/info.go
> +// GENERATED BY textFileToGoConst
Can be removed

2022-09-15 14:26 UTC, Trottoir approved these changes

2022-09-19 08:44 UTC, ASAPSegfault approved these changes

2022-09-19 12:08 UTC, SlnPons approved these changes

2022-09-19 12:10 UTC, merged