add zip format info link
massalabs/thyra pull request #113
Opened 2022-09-21 12:48 UTC by Thykof

2022-09-21 14:31 UTC, Trottoir approved these changes

2022-09-23 14:37 UTC, SebastienValla requested changes

2022-09-23 14:37 UTC, SebastienValla commented on resource/html/front/website.html
> +						<p><a href="https://github.com/massalabs/thyra#upload-a-webstite" target="_blank">Format info</a></p>
same thing add rel="noopener" with target_blank for safety issue

2022-09-23 14:48 UTC, SebastienValla approved these changes

2022-09-23 14:48 UTC, Thykof commented on pkg/front/website/html.go
> +					</div>
as we talk together, rel="noopener" is by default when target is _blank (https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener)

2022-09-27 07:18 UTC, SlnPons commented
@Thykof 2 comments: 
1. could you make the text smaller and grey please? (like the text info for the name above)
2. When I click on the link, I'm redirected to the readme but I can't see any section regarding the website upload. Are you sure you push the modification? Happy to help if needed

2022-09-27 12:23 UTC, Thykof commented
@SlnPons I have just pushed the work we did together. Juste to keep track: about the link to the readme, it will work when this PR will be merge into main branch.

2022-09-27 14:04 UTC, SlnPons approved these changes

2022-09-28 08:17 UTC, Thykof commented on resource/html/front/wallet.html
> +									placeholder="Wallte name"
good catch, fixed

2022-09-28 12:56 UTC, merged