81 backsc change upload chunk logic and fetching logic
massalabs/thyra pull request #153
Opened 2022-09-29 11:30 UTC by SebastienValla

We upload the first chunk with initializeWebsite in the dataEntry massa_web key of the websiteCreator contract
    Then for each following chunks, we append in the dataEntry massa_web key of the websiteCreator contract with appendBytesToWebsite
    Between each chunks, we are waiting for an event to assert that the chunk uploading has ended
    TO BE :
    Upload each chunk with the key : , (...) following the chunkId
    ex :
    dataEntry "massa_web0" => chunk 0 
    dataEntry "massa_web1" => chunk 1 
    dataEntry "massa_web2" => chunk 2 
We then fetch all massa_web key and reconstruct the final zip on Thyra

2022-09-29 13:30 UTC, ASAPSegfault approved these changes

2022-09-29 16:03 UTC, Trottoir requested changes

2022-09-29 16:04 UTC, Trottoir commented
We also need to merge our 2 SC versions before merging that one + replace `websiteStorer.wasm` : 
- https://github.com/massalabs/massa-examples-deployer/pull/1
- https://github.com/massalabs/massa-examples-deployer/pull/3

2022-09-30 07:13 UTC, SebastienValla commented on pkg/onchain/website/uploader.go
> +	chunkID string `json:"chunkID"` //nolint:all
when I put chunk_id the linter is saying "no underscore with Go" when I put chunkID the linter is saying to put chunk_id

2022-09-30 16:28 UTC, Trottoir commented
> We also need to merge our 2 SC versions before merging that one + replace `websiteStorer.wasm` :
> 
> * [[SC] - Add attributes in websiteDeployer contract massa-examples-deployer#1](https://github.com/massalabs/massa-examples-deployer/pull/1)
> * [2 backsc change upload chunk logic massa-examples-deployer#3](https://github.com/massalabs/massa-examples-deployer/pull/3)

Both branches have been merged manually by hand on the `2 sc change upload chunk logic massa-examples-deployer` branch

2022-10-03 07:39 UTC, Trottoir approved these changes

2022-10-03 09:41 UTC, merged