Update INSTALLATION.md
massalabs/thyra pull request #240
Opened 2022-11-03 14:18 UTC by SlnPons

Adding the scripts into the installation process to launch Thyra for all. 
Please add any details I've missed, these scripts are for non-dev so better add too much details that having them blocked :D

2022-11-04 08:10 UTC, Thykof commented on INSTALLATION.md
> +Download and open the file [here](https://github.com/massalabs/thyra/blob/main/scripts/macos_install.sh)
```suggestion
Download and open the file [here](https://github.com/massalabs/thyra/blob/main/scripts/macos_install.sh).
```

2022-11-04 08:10 UTC, Thykof commented on INSTALLATION.md
> +Download and open the file [here](https://github.com/massalabs/thyra/blob/main/scripts/linux_install.sh)
```suggestion
Download and open the file [here](https://github.com/massalabs/thyra/blob/main/scripts/linux_install.sh).
```

2022-11-04 08:10 UTC, Thykof commented on INSTALLATION.md
> +Download and open the file [here](https://github.com/massalabs/thyra/blob/main/scripts/thyra-installer.bat)
```suggestion
Download and open the file [here](https://github.com/massalabs/thyra/blob/main/scripts/thyra-installer.bat).
```

2022-11-08 09:48 UTC, ASAPSegfault requested changes

2022-11-08 09:48 UTC, ASAPSegfault commented on INSTALLATION.md
>  * If you have an Intel CPU (amd64), you can download your it [here](https://github.com/massalabs/thyra/releases/latest/download/thyra-server_darwin_amd64).
```suggestion
* If you have an Intel CPU (amd64), you can download your executable [here](https://github.com/massalabs/thyra/releases/latest/download/thyra-server_darwin_amd64).
```

2022-11-08 09:48 UTC, ASAPSegfault commented on INSTALLATION.md
>  * If you have an Intel Apple Silicon CPU M1, M1 Pro, M2... (arm64), you can download your it [here](https://github.com/massalabs/thyra/releases/latest/download/thyra-server_darwin_arm64).
```suggestion
* If you have an Intel Apple Silicon CPU M1, M1 Pro, M2... (arm64), you can download your executable [here](https://github.com/massalabs/thyra/releases/latest/download/thyra-server_darwin_arm64).
```

2022-11-08 09:48 UTC, ASAPSegfault commented on INSTALLATION.md
> +Simply use the link below to download and then open the file on your machine. The installation process will start and a success message will be displayed once done.
```suggestion
Simply use the link below to download and then open the file on your machine. The installation process will start and a success message will be displayed once done. 
Note that you must execute this script as an administrator.
```

2022-11-08 12:31 UTC, Thykof approved these changes

2022-11-08 12:34 UTC, ASAPSegfault approved these changes

2022-11-08 12:51 UTC, merged