add check if .html file exist in source of zip file, otherwise return Error
massalabs/thyra pull request #277
Opened 2022-11-21 09:32 UTC by B-Naoufal

… an error WebCreator-1005

2022-11-21 11:03 UTC, Thykof requested changes
There are some linter issues

2022-11-21 11:03 UTC, Thykof commented on int/api/websites/webcreator.go
> +		return createInternalServerError(errorCodeWebCreatorHtmlNotInSource, err.Error())
```suggestion
		return createInternalServerError(errorCodeWebCreatorHTMLNotInSource, err.Error())
```

2022-11-21 12:29 UTC, B-Naoufal commented
@Thykof just committed the suggestion modifications

2022-11-22 14:07 UTC, Thykof requested changes
there is a changed file when I run `go generate` I think we should commit it

2022-11-22 14:25 UTC, B-Naoufal commented
> 

Done missed go generate for embedded spec

2022-11-22 17:10 UTC, Thykof requested changes

2022-11-22 17:16 UTC, Thykof approved these changes

2022-11-22 17:22 UTC, thomas-senechal approved these changes

2022-11-22 21:07 UTC, gregLibert requested changes
:no_good: 
You should use the native function instead of creating your own find in array.

The small suggestion for code clarity is more nitpicking (I would not have shared it without another comment).

2022-11-22 21:07 UTC, gregLibert commented on int/api/websites/webcreator.go
> +func listArchiveContent(zipReader *zip.Reader) []string {
You function name is misleading, you should name it following what the code is doing.

My proposal:
```suggestion
func listFileName(zipReader *zip.Reader) []string {
```

2022-11-22 21:07 UTC, gregLibert commented on int/api/websites/webcreator.go
> +}
The best code is the one you're not writing : https://pkg.go.dev/golang.org/x/exp/slices#Index

2022-11-22 21:07 UTC, gregLibert commented on int/api/websites/webcreator.go
> +	if !contains(FilesOfArchive, "index.html") {
should be 
```suggestion
	if slice.Index(FilesOfArchive, "index.html") == -1 {
```

2022-11-23 12:20 UTC, gregLibert approved these changes
👏 good job!

2022-11-23 12:22 UTC, merged