154 https certificate
massalabs/thyra pull request #288
Opened 2022-11-22 14:27 UTC by peterjah

2022-12-01 15:44 UTC, gregLibert requested changes
:mag:

2022-12-02 09:13 UTC, peterjah commented on scripts/linux_install.sh
> +MKCERT_URL="https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
> Why not using the last version: https://dl.filippo.io/mkcert/latest?for=linux/amd64 ?

It is really what we want ? Imho its safer to set a specific version that we know is working well. and only update it if needed

2022-12-02 09:20 UTC, peterjah commented on int/api/server.go
> +		}
bien vu!

2022-12-02 12:53 UTC, gregLibert commented on scripts/linux_install.sh
> +MKCERT_URL="https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
Yeah, you're right. But in practice, I'm not sure that we will have the capacity to update it on a regular basis.
You make the call.

2022-12-02 13:38 UTC, peterjah commented on scripts/linux_install.sh
> +MKCERT_URL="https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
ok then lest take latest!

2022-12-02 14:29 UTC, gregLibert approved these changes
:clap: good job!

2022-12-06 09:20 UTC, 0xMazout approved these changes

2022-12-06 09:33 UTC, ASAPSegfault approved these changes
It works perfectly fine

2022-12-06 11:14 UTC, merged