Byte helper
massalabs/thyra pull request #316
Opened 2022-11-30 16:28 UTC by 0xMazout

Adding Byte Helper and updating Dns and Websites

2022-11-30 16:56 UTC, Thykof approved these changes
🤷 LGTM

2022-11-30 17:08 UTC, Thykof requested changes
please rename `StringtoByteArray` into `StringToByteArray`

2022-11-30 17:39 UTC, Thykof approved these changes
🤷 LGTM

2022-12-01 19:33 UTC, gregLibert requested changes
:no_good: the package helper is not properly named and it is useless.

You are using a StringToByteArray helping function that:
- involves the import of a new package
- need to write `helper.StringToByteArray(metaKey)` instead of simply `[]byte(metaKey)`

2022-12-01 19:33 UTC, gregLibert commented on pkg/helper/byteHelper.go
> +package helper
helper is very broad. What about convert ?

this will make your function usage cleaner:

```golang
...
convert.U64ToBytes(123)
...
```

2022-12-01 19:33 UTC, gregLibert commented on pkg/helper/byteHelper.go
> +package helper
All those helper as useless: you are only wrapping one or two lines of code...

2022-12-01 19:33 UTC, gregLibert commented on pkg/my/domain.go
> +		helper.StringToByteArray(ownedPrefix+wallet.Address))
[]byte(ownedPrefix+wallet.Address)

2022-12-01 19:33 UTC, gregLibert commented on pkg/my/domain.go
> +			Key:     helper.StringToByteArray(recordPrefix + domainNames[i]),
idem

2022-12-01 19:33 UTC, gregLibert commented on int/api/websites/all.go
> +				Address: string(record.CandidateValue), Key: helper.StringToByteArray(metaKey),
[]byte(metaKey)

2022-12-05 14:02 UTC, 0xMazout commented
Closed Features are moved in #317 

Need to delete the branch when 317 will be merged

2022-12-05 14:02 UTC, closed without merging