Add dns-address flag.
massalabs/thyra pull request #369
Opened 2022-12-28 16:08 UTC by thomas-senechal

2022-12-29 17:38 UTC, SlnPons commented
@thomas-senechal I don't see any comment on the PR, could we add the label "action:merge"?

2022-12-29 17:41 UTC, thomas-senechal commented
> @thomas-senechal I don't see any comment on the PR, could we add the label "action:merge"?

Oops.
In fact, I just forgot to put that PR in review. 
We now have to wait for 2 reviews before adding the "action:merge" label.

2022-12-30 15:49 UTC, gregLibert requested changes
:no_good: The readability of the code needs to be improved

2022-12-30 15:49 UTC, gregLibert commented on int/api/server.go
> +	os.Setenv(dns.DNSAddressEnvKey, dnsAddressPtr)
You should avoid to use the package name in the constant. It's redundant.

2022-12-30 15:49 UTC, gregLibert commented on int/api/websites/all.go
> +	addressesResult, err := ledger.Addresses(client, []string{dns.GetDNSAddress()})
Same here: Get and DNS are useless.

2022-12-30 15:49 UTC, gregLibert commented on pkg/onchain/dns/dns.go
> +}
```suggestion
const EnvKey = "THYRA_DNS_ADDRESS"

func Address() string {
	return os.Getenv(EnvKey)
}
```

2023-01-03 13:32 UTC, gregLibert approved these changes
:thinking:

2023-01-03 13:32 UTC, gregLibert commented on int/api/server.go
> +	var dnsAddressPtr string
What does Ptr mean ?

2023-01-03 13:36 UTC, thomas-senechal commented on int/api/server.go
> +	var dnsAddressPtr string
Fixed!

2023-01-03 13:52 UTC, B-Naoufal approved these changes

2023-01-03 14:30 UTC, thomas-senechal commented on int/api/server.go
> +		dnsAddress = "A15e47ChESAK1SdmGe3b92bybnBvMX2eFaxg23wn3rSdRzFHHGB"
Discussed in PM

2023-01-03 14:42 UTC, merged