1-click-install-ThyraApp-from-thyra
massalabs/thyra pull request #392
Opened 2023-01-06 14:54 UTC by B-Naoufal

- Download ThyraApp from release page : [ThyraApp](https://github.com/massalabs/Thyra-Menu-Bar-App)
- Unzip it and launch it within the installation script

2023-01-10 16:19 UTC, gregLibert requested changes
I don't see any logic to make thyra start with next OS reboot.
@SlnPons don't you think that this is something mandatory ?

2023-01-10 16:19 UTC, gregLibert commented on scripts/thyra-installer.py
> +THYRA_APP = "https://github.com/massalabs/Thyra-Menu-Bar-App/releases/download/v0.0.1/ThyraApp_windows-amd64.exe"
Why not using the latest version like for Thyra ?

2023-01-10 16:19 UTC, gregLibert commented on scripts/thyra-installer.py
>  THYRA_FILENAME = "thyra-server.exe"
Should be under THYRA_URL

2023-01-10 16:19 UTC, gregLibert commented on scripts/thyra-installer.py
> +    if os.path.exists(THYRA_APP_PATH):
Is it normal if it doesn't exist ? Is it possible ?

2023-01-11 17:22 UTC, B-Naoufal commented
> I don't see any logic to make thyra start with next OS reboot. @SlnPons don't you think that this is something mandatory ?

will be covered in https://github.com/massalabs/Thyra-Menu-Bar-App/issues/7

2023-01-12 12:00 UTC, gregLibert approved these changes
:+1:

2023-01-12 12:18 UTC, 0xMazout approved these changes
Great

2023-01-12 16:54 UTC, merged