Updates main github
massalabs/thyra pull request #417
Opened 2023-01-18 10:15 UTC by SlnPons

2023-01-18 10:29 UTC, SlnPons commented
Guys, if a builder from the community wants to participate to the project - how can they do? 
Did I remove too much?
(Lucas I didn't add the GCC installation for all OS to be consistent...feel free to correct this if it's wrong :/)

2023-01-18 15:21 UTC, gregLibert requested changes
:mag:

2023-01-18 15:21 UTC, gregLibert commented on INSTALLATION.md
> +The following installation guide allows you to perform these steps automatically using a simply script to run on your terminal.
```suggestion
The following installation guide allows you to perform these steps automatically using a simple script to run on your terminal.
```

2023-01-23 14:40 UTC, gregLibert approved these changes
:+1:

2023-01-23 14:40 UTC, merged