Fix for MIME type handling
massalabs/thyra pull request #434
Opened 2023-01-27 22:33 UTC by mickael-btc

Hello,

I have fixed an issue with the MIME type handling in the server. The problem was that the server was not properly handling MIME types for certain file extensions, which caused errors when loading scripts and other resources.

For example when uploading a website that was built with react, the javascript files weren’t accepted as valid javascript modules since thyra marked them as json.

I have added common MIME types i found on [MDM](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types). I updated the setContentType function to handle the vast majority of extensions.

I have tested the changes and they are working correctly. I would like to request that these changes be included in the main branch.

Thank you for your time and consideration.

2023-01-30 09:09 UTC, peterjah requested changes
Thanks for your contribution.
I think it would be better to not deal with these MIME types and directly use the mime package from go
https://pkg.go.dev/mime
it does quite the same thing as you:
```
		file := "test.html"
		ctype := mime.TypeByExtension(filepath.Ext(file))
		w.Header().Set("Content-Type", ctype)
```
The good think is you don't have to maintain this map of extensions/mime types

2023-01-30 16:17 UTC, peterjah commented
done here:
https://github.com/massalabs/thyra/pull/438

can you confirm it fits your needs !

2023-01-30 23:42 UTC, mickael-btc commented
Yes thank you !

2023-01-30 23:42 UTC, closed without merging

2023-01-31 09:52 UTC, peterjah commented
merged 
https://github.com/massalabs/thyra/pull/438