change addresses to new format
massalabs/thyra pull request #500
Opened 2023-03-01 14:01 UTC by SebastienValla

2023-03-02 13:30 UTC, peterjah commented on pkg/node/sendoperation/transaction/transaction.go
> +			RecipientAddress: "AU" + base58.CheckEncode(append(make([]byte, 1), t.recipientAddress...)),
`"AU" + base58.VersionedCheckEncode(t.recipientAddress..., 0)`

2023-03-02 13:37 UTC, peterjah requested changes
I think all conversion of address  from/to  bytes and string must be factorized.
maybe in an Address Object that will have fromPublicKey and fromPrivateKey methods

2023-03-03 13:58 UTC, peterjah approved these changes

2023-03-03 14:49 UTC, ASAPSegfault requested changes

2023-03-03 14:49 UTC, ASAPSegfault commented on pkg/node/sendoperation/callsc/callsc.go
> +	addressVersioned := append([]byte{byte(1)}, address...)
Should be versionedAddress to stay consistent with the rest (b58VersionedCheckEncode for example)

2023-03-03 15:06 UTC, ASAPSegfault approved these changes

2023-03-06 11:06 UTC, merged