added update plugin
massalabs/thyra pull request #648
Opened 2023-05-09 10:25 UTC by Pierregvx

2023-05-09 14:29 UTC, Thykof requested changes

2023-05-10 12:51 UTC, peterjah requested changes
There is no need for a new endpoint.
just use `POST /plugin-manager/%s/execute` with the option "update"

2023-05-10 14:05 UTC, peterjah approved these changes

2023-05-10 14:13 UTC, Thykof approved these changes

2023-05-10 14:17 UTC, Thykof requested changes
You need to change "update" to something else because now it's implemented https://github.com/massalabs/thyra/blob/main/api/test/robot_tests/plugin_manager/plugin_manager.robot#L181 ^^

2023-05-10 14:32 UTC, peterjah commented on api/test/robot_tests/plugin_manager/plugin_manager.robot
>  POST /plugin-manager/{id}/execute with NotImplemented update command
with NotImplemented update command => with unknown command

2023-05-10 14:37 UTC, Thykof commented
> You need to change "update" to something else because now it's implemented https://github.com/massalabs/thyra/blob/main/api/test/robot_tests/plugin_manager/plugin_manager.robot#L181 ^^

my bad, you can remove this test, test for invalid command already exists

2023-05-10 14:58 UTC, Thykof approved these changes

2023-05-10 14:58 UTC, merged