661 move the new windows installer
massalabs/thyra pull request #662
Opened 2023-05-15 08:40 UTC by thomas-senechal

2023-05-17 07:51 UTC, Thykof requested changes
here is my review of python code

2023-05-17 07:51 UTC, Thykof commented on installer/windows/build_installer.py
> +                "This script is only meant to be run on Windows. If you wish to run it anyway, use the '-f' flag."
just asking, in what case would we like to force build?

2023-05-17 07:51 UTC, Thykof commented on installer/windows/build_installer.py
> +        if not FORCE_BUILD:
```suggestion
        if not args.force_build:
```

2023-05-17 07:51 UTC, Thykof commented on installer/windows/build_installer.py
> +    VERSION = args.version
it might not be a good practice to modify global variable, I would have pass the value to the functions build_installer and create_wxs_file

2023-05-17 07:51 UTC, Thykof commented on installer/windows/build_installer.py
> +    FORCE_BUILD = args.force_build
```suggestion
```

2023-05-17 07:51 UTC, Thykof commented on installer/windows/build_installer.py
> +FORCE_BUILD = False
see comment bellow

```suggestion
```

2023-05-17 07:51 UTC, Thykof commented on installer/windows/build_installer.py
there is not try catch around main function, what happen if install_dependencies fail? do we want to handle this kind of error? If no, ignore my comment

2023-05-22 13:13 UTC, peterjah approved these changes

2023-05-23 10:27 UTC, Thykof approved these changes

2023-05-23 10:28 UTC, merged