add update unit test
massalabs/thyra pull request #670
Opened 2023-05-19 08:06 UTC by Pierregvx

2023-05-19 08:28 UTC, Pierregvx commented
run the test with with `go test ./api/test -v`

2023-05-22 10:00 UTC, peterjah commented on pkg/plugin/manager.go
> +	go func() {
move this function implementation elsewhere with an appropriate name!

2023-05-22 10:06 UTC, peterjah requested changes

2023-05-22 10:06 UTC, peterjah commented on pkg/plugin/manager.go
> +func findPluginByName(name string, plugins []store.Plugin) *store.Plugin {
move this func in pkg/store

2023-05-22 12:57 UTC, peterjah commented on pkg/store/store.go
> +	interval := 10
define this directly in FetchStorePeriodically, or even in global constant

2023-05-22 13:02 UTC, peterjah requested changes

2023-05-22 14:57 UTC, Thykof requested changes

2023-05-24 12:22 UTC, merged