693 change dns to station.massa
massalabs/thyra pull request #725
Opened 2023-06-06 16:51 UTC by Thykof

2023-06-08 07:40 UTC, peterjah requested changes

2023-06-08 07:40 UTC, peterjah commented on pkg/config/network.go
> +func GetMassaStationURL() string {
useless Getter, just put a uppercase to `massaStationURL`

2023-06-08 07:40 UTC, peterjah commented on int/systray/systray.go
> +			openURL(&stationGUI, "http://station.massa/thyra/home")
use massaStationURL variable from network.go

2023-06-08 07:40 UTC, peterjah commented on pkg/node/sendoperation/sendoperation.go
> +const WalletPluginURL = "http://station.massa/thyra/plugin/massalabs/wallet/rest/wallet/"
use massaStationURL variable from network.go

2023-06-08 13:54 UTC, gregLibert reviewed
This PR is big by nature. But it contains modifications having nothing to do with the renaming task...
All is fine, except for the postman question, maybe we should simply remove them. but this is not blocking

2023-06-09 15:26 UTC, Thykof commented on api/test/massa_endpoints.postman_collection.json
> +					"raw": "http://station.massa/massa/addresses?addresses=AU12ajG8wNxcdv7V7wEssGfQSaU5YX6oQQ9Sj686vukvfp2LuUGz5&addresses=AU12tkFEY2WTfHA4H8F5wPWp4JNKCBNyq5AhLdZj7udfBYoRtp1qS",
no, not yet, and we have in mind to generate the postman collection automatically from the swagger file. 

the changes here is simple: replace my.massa by station.massa.

2023-06-09 15:27 UTC, Thykof commented
The CI is red because of the test-api-robot that doesn't pass. The fix is in the following PR: #724

2023-06-10 04:58 UTC, gregLibert approved these changes

2023-06-10 04:59 UTC, merged