727 check for update feature
massalabs/thyra pull request #728
Opened 2023-06-07 16:26 UTC by thomas-senechal

2023-06-09 07:57 UTC, peterjah commented on int/systray/update/update_check.go
> +	request, err := http.NewRequestWithContext(context.Background(), http.MethodGet, updateCheckURL, strings.NewReader(""))
why NewRequestWithContext is used for ?? compared to a simple http.get(...) ?

2023-06-09 12:21 UTC, gregLibert requested changes

2023-06-09 12:21 UTC, gregLibert commented on int/systray/update/update_check.go
> +		log.Println("Error checking for updates:", err)
```suggestion
		log.Println("Error getting last version:", err)
```

2023-06-09 12:21 UTC, gregLibert commented on int/systray/update/update_dialog.go
> +		"Cancel",
```suggestion
		"Ignore",
```

2023-06-12 08:02 UTC, gregLibert requested changes

2023-06-12 08:02 UTC, gregLibert commented on int/systray/update/update_dialog.go
> +			break
```suggestion
			return w
```

2023-06-12 08:02 UTC, gregLibert commented on int/systray/update/update_dialog.go
> +		"An update is available for MassaStation. Do you want to update now?",
```suggestion
		"An update is available for MassaStation. Do you want to update it now?",
```

2023-06-12 08:02 UTC, gregLibert commented on int/systray/update/update_dialog.go
> +		"Ignore",
```suggestion
		"Later",
```

2023-06-12 09:58 UTC, gregLibert approved these changes

2023-06-12 16:36 UTC, gregLibert commented
@thomas-senechal can you resolve the conflicts?

2023-06-13 09:26 UTC, merged