734 update readme
massalabs/thyra pull request #735
Opened 2023-06-09 14:26 UTC by thomas-senechal

2023-06-12 12:58 UTC, SlnPons requested changes

2023-06-12 12:58 UTC, SlnPons commented on README.md
> +### Install plugins
```suggestion
### Modules (aka Plugins)```

2023-06-13 10:12 UTC, SlnPons commented on README.md
> +MassaStation is a module manager. It enables everyone to use, create and enjoy different modules to add features to the Massa blockchain.
```suggestion
MassaStation is a module manager. It enables everyone to use, create and enjoy different modules to activate features to the Massa blockchain.
```

2023-06-13 10:45 UTC, SlnPons commented on README.md
> +The module will be installed and activated after a few seconds. You can now use it in MassaStation !
```suggestion
The module will be automatically installed and activated after a few seconds directly in your Station. Browse MassaStation store to find the module you need.
```

2023-06-13 10:45 UTC, SlnPons commented on README.md
> +If you are working on a module, you can install it manually in MassaStation:
```suggestion
If you are working on a module, you can install it manually to test it using MassaStation:
```

2023-06-13 12:40 UTC, SlnPons approved these changes

2023-06-14 07:29 UTC, peterjah approved these changes

2023-06-14 07:47 UTC, merged